spring.datasource.url=jdbc:sqlite:kanban.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Exécuter le fichier kanban_colors.sqlite au démarrage
spring.sql.init.mode=always
spring.sql.init.data-locations=file:kanban_colors.sqlite
spring.jpa.defer-datasource-initialization=true
